# Generated by Django 5.2.7 on 2025-10-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_dish_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
