# Generated by Django 5.2.7 on 2025-10-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_alter_dish_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.CharField(default="s", max_length=100),
            preserve_default=False,
        ),
    ]
