# Generated by Django 5.2.7 on 2025-10-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_remove_menu_week_days_menuday"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="location",
            field=models.CharField(default="new york", max_length=100),
            preserve_default=False,
        ),
    ]
